mapping = {
    "'s-Hertogenbosch": "Den Bosch",
    "[zonder plaats]": "onbekend",
    "[?]": "onbekend",
    "[Alken]": "Alken",
    "[Duitsland]": "Duitsland",
    "[Erlangen?]": "Erlangen",
    "[geen plaats]": "onbekend",
    "[Geen plaats]": "onbekend",
    "[Giessen]": "Giessen",
    "[Groningen]": "Groningen",
    "[Haarlem]": "Haarlem",
    "[Lausanne]": "Lausanne",
    "[Leiden]": "Leiden",
    "[Marburg]": "Marburg",
    "[Middelharnis]": "Middelharnis",
    "[Nederland]": "Nederland",
    "[Neuchâtel]": "Neuchâtel",
    "[onbekend]": "Onbekend",
    "[Orleans]": "Orléans",
    "[Rotterdam]": "Rotterdam",
    "[S.l.]": "onbekend",
    "[S.l.] (Sensenfabrik?)": "onbekend",
    "[Utrecht]": "Utrecht",
    "[Wittenberg?]": "Wittenberg",
    "[zonder paats]": "zonder plaats",
    "[Zonder plaats]": "zonder plaats",

    "Aan boord van Z.M. Brik Gier": "Aan boord van Z.M. Brik Gier",
    "Aan boord van Z.M. Brik Zwaluw": "Aan boord van Z.M. Brik Zwaluw",

    "Alkmaar": "Alkmaar",
    "Amersfoort": "Amersfoort",
    "Amsterdam": "Amsterdam",
    "Angerorth": "Angerort",
    "Angers": "Angers",
    "Antwerpen": "Antwerpen",
    "Appingedam": "Appingedam",
    "Arendsee": "Arendsee",
    "Arnhem": "Arnhem",
    "Aruba": "Aruba",
    "Assen": "Assen",
    "Atrecht": "Atrecht",
    "Augsburg": "Augsburg",
    "Avondsee": "Avonddorp",
    "Baarn": "Baarn",
    "Batavia": "Batavia",
    "Bautzen": "Bautzen",
    "Bentheim": "Bentheim",
    "Bergen op Zoom": "Bergen op Zoom",
    "Berlijn": "Berlijn",
    "Bern": "Bern",
    "Bernikow": "Bernikow",
    "Blois": "Blois",
    "Boldekow": "Boldekow",
    "Bonn": "Bonn",
    "Boskoop": "Boskoop",
    "Böttingen": "Böttingen",
    "Bourges": "Bourges",
    "Bovenkarspel": "Bovenkarspel",
    "Breda": "Breda",
    "Brussel": "Brussel",
    "Bunchnitz(?)": "Bunznitz",
    "Busow": "Busow",

    "Curacao": "Curaçao",
    "Curaçao": "Curaçao",

    "Darmstadt": "Darmstadt",
    "De Haag": "Den Haag",
    "Delfshaven": "Delfshaven",
    "Delft": "Delft",
    "Demerary": "Demerary",
    "Den Bosch": "Den Bosch",
    "Den haag": "Den Haag",
    "Den Haag": "Den Haag",
    "Den Haag e.a.": "Den Haag",
    "Deventer": "Deventer",
    "Dittmannsdorf": "Dittmannsdorf",
    "Dodewaard": "Dodewaard",
    "Dordrecht": "Dordrecht",
    "Douai": "Douai",
    "Dresden": "Dresden",
    "Dresden, Den Haag": "Dresden",
    "Duisburg": "Duisburg",
    "Duivenvoorde": "Duivenvoord", ##het kasteel?
    "Edam": "Edam",
    "Ede": "Ede",
    "Enkhuizen": "Enkhuizen",
    "Enkhuizen e.a.": "Enkhuizen",
    "Erlangen": "Erlangen",
    "Essequebo": "Essequibo",

    "Frankfurt": "Frankfurt",
    "Frankrijk": "Frankrijk",

    "Frauenwald": "Frauenwald",
    "Fraustadt": "Fraustadt",

    "Geertruidenberg": "Geertruidenberg",
    "Gelderen": "Gelderen",
    "Genève": "Genève",
    "Gent": "Gent",
    "Giessen": "Giessen",
    "Goes": "Goes",
    "Gorinchem": "Gorinchem",
    "Gotha": "Gotha",
    "Gouda": "Gouda",
    "Greiffenberg": "Greiffenberg",
    "Groeneveld": "Groeneveld",
    "Groningen": "Groningen",
    "Grosthuizen": "Grosthuizen",
    "Grunowitz": "Grunowitz",
    "Grünowitz": "Grunowitz",

    "Guyane": "Guyane",

    "Haarlem": "Haarlem",
    "Haastrecht": "Haastrecht",
    "Harderwijk": "Harderwijk",
    "Harenburch": "Harenburg",
    "Harlingen": "Harlingen",
    "Hasselt": "Hasselt",
    "Hellevoetsluis": "Hellevoetsluis",
    "Heyen": "Heyen",
    "Hildburghausen": "Hildburghausen",
    "Hillegom": "Hillegom",
    "Hongarije": "Hongarije",
    "Hoofdplaat": "Hoofdplaat",
    "Hoogeveen": "Hoogeveen",
    "Höttingen": "Höttingen",
    "Houten": "Houten",

    "Indische Oceaan": "Indische Oceaan",

    "Jamburg": "Jamburg",
    "Judenliege(?)": "Judenliege",

    "Kaub": "Kaub",
    "Keulen": "Keulen",
    "Kleef": "Kleef",

    "Königsberg": "Kaliningrad",
    "Königsberg (Neumark)": "Chojna",
    "Königsberg (Neumark) [e.a.]": "Chojna",

    "Koningslust": "Koningslust",
    "Krauschow": "Krauschow",
    "Krefeld": "Krefeld",
    "Krummendorf": "Krummendorf",

    "La Guaira": "La Guaira",
    "Lausanne": "Lausanne",
    "Leer": "Leer",
    "Leeuwarden": "Leeuwarden",
    "Legewitz(?)": "Legewitz",
    "Leiden": "Leiden",
    "Leiderdorp": "Leiderdorp",
    "Leipzig": "Leipzig",
    "Leyduin": "Leyduin",
    "Lith": "Lith",
    "Lochem": "Lochem",
    "Londen": "Londen",
    "Lopik": "Lopik",

    "Maarssen": "Maarssen",
    "Marburg": "Marburg",
    "Medemblik": "Medemblik",
    "Memmingen": "Memmingen",
    "Meppel": "Meppel",
    "Middelburg": "Middelburg",
    "Middelharnis": "Middelharnis",
    "Middelstum": "Middelstum",
    "Mijnsherenland": "Mijnsheerenland",
    "Mosbach": "Mosbach",

    "München": "München",
    "München": "München",
    "Münster": "Münster",

    "Neederbosch [= Neerbosch]": "Neerbosch",
    "Neerijnen": "Neerijnen",
    "Neinbühl": "Neinbühl",
    "Neuchâtel": "Neuchâtel",
    "Neuenburg": "Neuenburg",
    "Neuenstein": "Neuenstein",
    "Neurenberg": "Nuremberg",
    "Neustadt an der Aisch": "Neustadt an der Aisch",
    "Nieuwenhoorn": "Nieuwenhoorn",
    "Nijmegen": "Nijmegen",

    "Nürnberg": "Nuremberg",
    "Nürnberg [e.a.]": "Nuremberg",

    "öhringen": "Öhringen",
    "Öhringen": "Öhringen",

    "Olst": "Olst",
    "Olst [e.a.]": "Olst",

    "Oosterhout": "Oosterhout",
    "Opperdoes": "Opperdoes",

    "öringhen": "Öhringen",

    "Orléans": "Orléans",

    "Ouderkerk": "Ouderkerk aan den IJssel",
    "Ouderkerk aan de IJssel": "Ouderkerk aan den IJssel",
    "Ouderkerk aan den IJssel": "Ouderkerk aan den IJssel",

    "Overveen": "Overveen",

    "Palck bei Züllichau": "Sulechów",

    "Paramaribo": "Paramaribo",
    "Parijs": "Parijs",

    "Prenzlau": "Prenzlau",
    "Prenzlow": "Prenzlau",

    "Raamsdonk": "Raamsdonk",
    "Regensburg": "Regensburg",
    "Remagen": "Remagen",
    "Remangen": "Remagen",
    "Rijswijk": "Rijswijk",
    "Rotterdam": "Rotterdam",

    "s.l.": "onbekend",

    "Santpoort": "Santpoort",
    "Sassenheim": "Sassenheim",
    "Saumur": "Saumur",
    "Schaumburg": "Schaumburg",
    "Schiedam": "Schiedam",
    "Schierzig": "Schierzig",
    "Schleusingen": "Schleusingen",
    "Schonauwen": "Schönauwen",
    "Schönermark": "Schönermark",
    "Schwäbisch Hall": "Schwäbisch Hall",
    "Schwäbische Hall": "Schwäbisch Hall",
    "Schwiebus": "Świebodzin",

    "Semarang": "Semarang",
    "Sliedrecht": "Sliedrecht",
    "Smyrna": "İzmir",
    "Sommelsdijk": "Sommelsdijk",
    "St. Petersburg": "Sint Petersburg",
    "Steenwijk": "Steenwijk",
    "Stuttgart": "Stuttgart",
    "Suriname": "Suriname",

    "Thierhaupten": "Thierhaupten",
    "Tiel": "Tiel",
    "Triëst": "Trieste",
    "Tübingen": "Tübingen",

    "Utrecht": "Utrecht",
    "Utrecht [e.a.]": "Utrecht",

    "Velbert": "Velbert",
    "Villeneuve": "Villeneuve",
    "Vlissingen": "Vlissingen",
    "Voorburg": "Voorburg",

    "Waardenburg": "Waardenburg",
    "Wassenaar (Persijn)": "Wassenaar",
    "Weimar": "Weimar",
    "Westervoorde": "Westervoort",
    "Westzaandam": "Zaandam",
    "Wimpfen": "Bad Wimpfen",
    "Winterswijk": "Winterswijk",

    "Zeist": "Zeist",
    "Zierikzee": "Zierikzee",

    "Zonder plaats": "Zonder plaats",

    "Züllichau": "Sulechów",
    "Züllichau": "Sulechów",

    "Zutphen": "Zutphen",
    "Zwolle": "Zwolle",
}
##lat then long
coordinate_mapping = {
" [zonder plaats]":(),
"Aan boord van Z.M. Brik Gier":(),
"Aan boord van Z.M. Brik Zwaluw":(),
"Alken":(),
"Alkmaar":(),
"Amersfoort":(),
"Amsterdam":(),
"Angerort":(),
"Angers":(),
"Antwerpen":(),
"Appingedam":(),
"Arendsee":(),
"Arnhem":(),
"Aruba":(),
"Assen":(),
"Atrecht":(),
"Augsburg":(),
"Avonddorp":(),
"Baarn":(),
"Bad Wimpfen":(),
"Batavia":(),
"Bautzen":(),
"Bentheim":(),
"Bergen op Zoom":(),
"Berlijn":(),
"Bern":(),
"Bernikow":(),
"Blois":(),
"Boldekow":(),
"Bonn":(),
"Boskoop":(),
"Böttingen":(),
"Bourges":(),
"Bovenkarspel":(),
"Breda":(),
"Brussel":(),
"Bunznitz":(),
"Busow":(),
"Chojna":(),
"Curaçao":(),
"Darmstadt":(),
"Delfshaven":(),
"Delft":(),
"Demerary":(),
"Den Bosch":(),
"Den Haag":(),
"Deventer":(),
"Dittmannsdorf":(),
"Dodewaard":(),
"Dordrecht":(),
"Douai":(),
"Dresden":(),
"Duisburg":(),
"Duitsland":(),
"Duivenvoord":(),
"Edam":(),
"Ede":(),
"Enkhuizen":(),
"Erlangen":(),
"Essequibo":(),
"Frankfurt":(),
"Frankrijk":(),
"Frauenwald":(),
"Fraustadt":(),
"Geertruidenberg":(),
"Gelderen":(),
"Genève":(),
"Gent":(),
"Giessen":(),
"Goes":(),
"Gorinchem":(),
"Gotha":(),
"Gouda":(),
"Greiffenberg":(),
"Groeneveld":(),
"Groningen":(),
"Grosthuizen":(),
"Grunowitz":(),
"Guyane":(),
"Haarlem":(),
"Haastrecht":(),
"Harderwijk":(),
"Harenburg":(),
"Harlingen":(),
"Hasselt":(),
"Hellevoetsluis":(),
"Heyen":(),
"Hildburghausen":(),
"Hillegom":(),
"Hongarije":(),
"Hoofdplaat":(),
"Hoogeveen":(),
"Höttingen":(),
"Houten":(),
"Indische Oceaan":(),
"İzmir":(),
"Jamburg":(),
"Judenliege":(),
"Kaliningrad":(),
"Kaub":(),
"Keulen":(),
"Kleef":(),
"Koningslust":(),
"Krauschow":(),
"Krefeld":(),
"Krummendorf":(),
"La Guaira":(),
"Lausanne":(),
"Leer":(),
"Leeuwarden":(),
"Legewitz":(),
"Leiden":(),
"Leiderdorp":(),
"Leipzig":(),
"Leyduin":(),
"Lith":(),
"Lochem":(),
"Londen":(),
"Lopik":(),
"Maarssen":(),
"Marburg":(),
"Medemblik":(),
"Memmingen":(),
"Meppel":(),
"Middelburg":(),
"Middelharnis":(),
"Middelstum":(),
"Mijnsheerenland":(),
"Mosbach":(),
"München":(),
"Münster":(),
"Nederland":(),
"Neerbosch":(),
"Neerijnen":(),
"Neinbühl":(),
"Neuchâtel":(),
"Neuenburg":(),
"Neuenstein":(),
"Neustadt an der Aisch":(),
"Nieuwenhoorn":(),
"Nijmegen":(),
"Nuremberg":(),
"Öhringen":(),
"Olst":(),
"Onbekend":(),
"Oosterhout":(),
"Opperdoes":(),
"Orléans":(),
"Ouderkerk aan den IJssel":(),
"Overveen":(),
"Paramaribo":(),
"Parijs":(),
"Prenzlau":(),
"Raamsdonk":(),
"Regensburg":(),
"Remagen":(),
"Rijswijk":(),
"Rotterdam":(),
"Santpoort":(),
"Sassenheim":(),
"Saumur":(),
"Schaumburg":(),
"Schiedam":(),
"Schierzig":(),
"Schleusingen":(),
"Schönauwen":(),
"Schönermark":(),
"Schwäbisch Hall":(),
"Semarang":(),
"Sint Petersburg":(),
"Sliedrecht":(),
"Sommelsdijk":(),
"Steenwijk":(),
"Stuttgart":(),
"Sulechów":(),
"Suriname":(),
"Świebodzin":(),
"Thierhaupten":(),
"Tiel":(),
"Trieste":(),
"Tübingen":(),
"Utrecht":(),
"Velbert":(),
"Villeneuve":(),
"Vlissingen":(),
"Voorburg":(),
"Waardenburg":(),
"Wassenaar":(),
"Weimar":(),
"Westervoort":(),
"Winterswijk":(),
"Wittenberg":(),
"Zaandam":(),
"Zeist":(),
"Zierikzee":(),
"Zutphen":(),
"Zwolle":()
}